name: glowhair
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_typeahead: ^5.2.0
  data_table_2: ^2.5.7
  fl_chart: ^0.68.0
  table_calendar: ^3.1.2
  http: ^1.4.0
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  flutter_riverpod: ^2.5.1
  provider: ^6.1.5
  shared_preferences: ^2.2.3
  connectivity_plus: ^6.0.3
  iconsax: ^0.0.8
  shimmer: ^3.0.0
  google_fonts: ^6.3.0
  intl: ^0.20.0
  velocity_x: ^4.3.1
  flutter_svg: ^2.0.7
  file_picker: ^8.0.3
  path: ^1.9.0
  path_provider: ^2.1.4

  http_parser: ^4.0.2
  open_filex: ^4.5.0
  image_picker: ^1.1.2
  pdf: ^3.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/loginbg.png
    - assets/chatbotimg.png
    - assets/boyicon.png
    - assets/girlicon.png
    - assets/sampledoctor.png
    - assets/karurlogo.png



